name: Quick Check

on:
  push:
    branches: [ "*" ]  # Run on all branches
  pull_request:
    branches: [ main, develop ]

jobs:
  quick-test:
    name: Quick Build & Test Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Setup Node.js & pnpm
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2-dev \
          libpulse-dev \
          libgtk-3-dev \
          webkit2gtk-4.0 \
          libayatana-appindicator3-dev \
          librsvg2-dev
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          src-tauri/target
          node_modules
        key: quick-${{ runner.os }}-${{ hashFiles('src-tauri/Cargo.lock', 'pnpm-lock.yaml') }}
        restore-keys: |
          quick-${{ runner.os }}-
    
    - name: Install frontend dependencies
      run: pnpm install
    
    - name: TypeScript check
      run: pnpm run build
    
    - name: Rust check (compilation)
      run: |
        cd src-tauri
        cargo check --all-targets
    
    - name: Rust test (quick subset)
      run: |
        cd src-tauri
        # Run only fast tests, skip integration tests
        cargo test --lib
      env:
        RUST_BACKTRACE: 1